spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
spring.application.name=paiement-Service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
security.basic.enable=false
server.port=9097
spring.cloud.config.enabled=false

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=paiement-group-v4
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.alten.back.events

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
security.ignored=/**